<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('client_profiles', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('preferred_location')->nullable();$t->decimal('preferred_budget',12,2)->nullable();$t->string('language')->default('en');$t->timestamps();});
Schema::create('provider_profiles', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('provider_type')->default('individual');$t->string('business_name')->nullable();$t->string('national_id')->nullable();$t->string('kra_pin')->nullable();$t->string('contact_phone')->nullable();$t->string('whatsapp_phone')->nullable();$t->string('verification_status')->default('unverified');$t->boolean('is_makeja_managed')->default(false);$t->timestamps();});
Schema::create('property_categories', function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('property_types', function(Blueprint $t){$t->id();$t->foreignId('property_category_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('slug')->unique();$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('locations', function(Blueprint $t){$t->id();$t->string('country')->default('Kenya');$t->string('county')->nullable()->index();$t->string('town')->nullable()->index();$t->string('estate')->nullable()->index();$t->string('landmark')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->timestamps();});
} public function down(): void { Schema::dropIfExists('locations'); Schema::dropIfExists('property_types'); Schema::dropIfExists('property_categories'); Schema::dropIfExists('provider_profiles'); Schema::dropIfExists('client_profiles'); } };
