<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('saved_listings', function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('listing_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['user_id','listing_id']);});
Schema::create('inquiries', function(Blueprint $t){$t->id();$t->foreignId('listing_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('name')->nullable();$t->string('phone')->nullable();$t->text('message')->nullable();$t->string('status')->default('new');$t->timestamps();});
Schema::create('viewing_requests', function(Blueprint $t){$t->id();$t->foreignId('listing_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->date('preferred_date')->nullable();$t->string('preferred_time')->nullable();$t->text('message')->nullable();$t->string('status')->default('pending');$t->timestamps();});
Schema::create('reported_listings', function(Blueprint $t){$t->id();$t->foreignId('listing_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('reason');$t->text('details')->nullable();$t->string('status')->default('open');$t->foreignId('resolved_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('resolved_at')->nullable();$t->timestamps();});
Schema::create('tenants', function(Blueprint $t){$t->id();$t->foreignId('unit_id')->constrained()->cascadeOnDelete();$t->foreignId('provider_id')->constrained('provider_profiles')->cascadeOnDelete();$t->string('name');$t->string('phone')->nullable();$t->string('email')->nullable();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->decimal('monthly_rent',12,2)->default(0);$t->string('status')->default('active');$t->timestamps();});
Schema::create('rent_ledgers', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('unit_id')->constrained()->cascadeOnDelete();$t->string('period_month');$t->decimal('amount_due',12,2)->default(0);$t->decimal('amount_paid',12,2)->default(0);$t->date('due_date')->nullable();$t->timestamp('paid_at')->nullable();$t->string('status')->default('pending');$t->timestamps();});
Schema::create('maintenance_requests', function(Blueprint $t){$t->id();$t->foreignId('property_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('unit_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('provider_id')->nullable()->constrained('provider_profiles')->nullOnDelete();$t->string('title');$t->string('category')->nullable();$t->text('description')->nullable();$t->string('priority')->default('normal');$t->string('status')->default('open');$t->decimal('cost_estimate',12,2)->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamps();});
Schema::create('subscription_plans', function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->decimal('price',12,2)->default(0);$t->string('billing_cycle')->default('monthly');$t->integer('unit_limit')->nullable();$t->json('features')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('provider_subscriptions', function(Blueprint $t){$t->id();$t->foreignId('provider_id')->constrained('provider_profiles')->cascadeOnDelete();$t->foreignId('subscription_plan_id')->constrained()->restrictOnDelete();$t->string('status')->default('inactive');$t->timestamp('starts_at')->nullable();$t->timestamp('ends_at')->nullable();$t->unsignedBigInteger('last_payment_id')->nullable();$t->timestamps();});
Schema::create('payments', function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('provider_id')->nullable()->constrained('provider_profiles')->nullOnDelete();$t->nullableMorphs('payable');$t->decimal('amount',12,2);$t->string('currency')->default('KES');$t->string('method')->default('mpesa_stk');$t->string('status')->default('pending');$t->string('reference')->nullable()->index();$t->string('description')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();});
Schema::create('mpesa_transactions', function(Blueprint $t){$t->id();$t->foreignId('payment_id')->constrained()->cascadeOnDelete();$t->string('phone');$t->decimal('amount',12,2);$t->string('merchant_request_id')->nullable()->index();$t->string('checkout_request_id')->nullable()->index();$t->string('mpesa_receipt_number')->nullable()->index();$t->string('result_code')->nullable();$t->text('result_desc')->nullable();$t->string('status')->default('processing');$t->json('raw_request')->nullable();$t->json('raw_response')->nullable();$t->json('callback_payload')->nullable();$t->timestamps();});
Schema::create('mpesa_callbacks', function(Blueprint $t){$t->id();$t->string('checkout_request_id')->nullable()->index();$t->string('merchant_request_id')->nullable();$t->json('payload');$t->timestamp('processed_at')->nullable();$t->timestamps();});
} public function down(): void { foreach(['mpesa_callbacks','mpesa_transactions','payments','provider_subscriptions','subscription_plans','maintenance_requests','rent_ledgers','tenants','reported_listings','viewing_requests','inquiries','saved_listings'] as $table) Schema::dropIfExists($table); } };
