<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('properties', function(Blueprint $t){$t->id();$t->foreignId('provider_id')->nullable()->constrained('provider_profiles')->nullOnDelete();$t->foreignId('property_category_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('property_type_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('location_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('ownership_status')->default('community_added');$t->string('claim_status')->default('unclaimed');$t->string('address')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('property_claims', function(Blueprint $t){$t->id();$t->foreignId('property_id')->constrained()->cascadeOnDelete();$t->foreignId('provider_id')->constrained('provider_profiles')->cascadeOnDelete();$t->string('status')->default('pending');$t->text('claim_note')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('reviewed_at')->nullable();$t->timestamps();});
Schema::create('units', function(Blueprint $t){$t->id();$t->foreignId('property_id')->constrained()->cascadeOnDelete();$t->string('unit_name');$t->string('unit_type');$t->unsignedSmallInteger('bedrooms')->nullable();$t->unsignedSmallInteger('bathrooms')->nullable();$t->string('floor')->nullable();$t->string('size_label')->nullable();$t->decimal('rent_amount',12,2)->nullable();$t->decimal('sale_amount',12,2)->nullable();$t->decimal('deposit_amount',12,2)->nullable();$t->string('status')->default('available')->index();$t->text('notes')->nullable();$t->timestamps();});
Schema::create('listings', function(Blueprint $t){$t->id();$t->foreignId('property_id')->constrained()->cascadeOnDelete();$t->foreignId('unit_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('listing_intent')->default('rent')->index();$t->decimal('price',12,2)->default(0);$t->decimal('deposit',12,2)->default(0);$t->string('currency')->default('KES');$t->string('status')->default('pending_approval')->index();$t->string('trust_status')->default('community_added')->index();$t->date('available_from')->nullable();$t->timestamp('expires_at')->nullable();$t->string('contact_name')->nullable();$t->string('contact_phone')->nullable();$t->string('contact_whatsapp')->nullable();$t->unsignedBigInteger('views_count')->default(0);$t->boolean('is_featured')->default(false);$t->timestamps();});
Schema::create('listing_images', function(Blueprint $t){$t->id();$t->foreignId('listing_id')->constrained()->cascadeOnDelete();$t->string('url');$t->string('disk')->default('supabase');$t->string('path')->nullable();$t->string('caption')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->boolean('is_cover')->default(false);$t->timestamps();});
} public function down(): void { Schema::dropIfExists('listing_images'); Schema::dropIfExists('listings'); Schema::dropIfExists('units'); Schema::dropIfExists('property_claims'); Schema::dropIfExists('properties'); } };
